###########
# Dataset #
###########
data_root: './data/CIFAR10/'
batch_size: 100
dataset: 'cifar10'
num_workers: 8
eval_batch_size: 50
eval_num_workers: 4
batch_iter: 1

nb_classes: 10

# Corruption Parameters
corruption_percent: 0.4
asymmetric_noise: False 

x_c: 3      #Channel
x_h: 32     #Image height
x_w: 32     #Image Width
y_c: 10     #Length of output classes

device: 'cuda:0'

##############
# SPR params #
##############

#Model customized for ssl:
net: 'resnet_simclr18'

#only 25% buffer being used compared to SPR
purified_buffer_size: 500
purified_buffer_q_poa: 0.0 # power of allocation

delayed_buffer_size: 500
delayed_buffer_q_poa: 0.0 # power of allocation

E_max: 5

#epochs SPR-->CNLL: 5000-->150
expert_train_epochs: 150
expert_batch_size: 500

base_train_epochs: 100
base_batch_size: 500

ft_epochs: 8
ft_batch_size: 100

# NTXENTLoss SimCLRparams
use_cosine_similarity: True
temperature: 0.5
projection_out_dim: 256

#########
# Train #
#########
optimizer:
  type: Adam
  options:
    lr: 0.005

lr_scheduler:
  type: CosineAnnealingLR
  options:
    eta_min: 0
    last_epoch: -1

optimizer_ft:
  type: Adam
  options:
    lr: 0.005

lr_scheduler_ft:
  type: StepLR
  options:
    step_size: 40
    gamma: 0.1


clip_grad:
  type: value
  options:
    clip_value: 0.5

########
# Eval #
########

eval: True
